'use client'
import type { Metadata } from "next";
import "./globals.css";
import { useState } from "react";



// export const metadata: Metadata = {
//   title: "Countries",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [dark , setDark] = useState(false)
  function toggleDarkMode(){
    if(dark){
      setDark(false)
    }
    else{
      setDark(true)
    }
  }
  return (
    <html lang="en">
      <body className={`${dark ? "dark" : "light"}`}>
        <div className=" bg-elements font-Nunito py-5 drop-shadow-md px-5 lg:px-0">
            <div className='container mx-auto flex justify-between items-centerd'>
                  <p className='font-black lg:text-xl text-text'>Where in the world?</p>
                  <div className='flex items-center gap-3'>
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="size-6 stroke-text fill-text">
                      <path strokeLinecap="round" strokeLinejoin="round" d="M21.752 15.002A9.72 9.72 0 0 1 18 15.75c-5.385 0-9.75-4.365-9.75-9.75 0-1.33.266-2.597.748-3.752A9.753 9.753 0 0 0 3 11.25C3 16.635 7.365 21 12.75 21a9.753 9.753 0 0 0 9.002-5.998Z" />
                  </svg>
                  <button onClick={toggleDarkMode} className='text-text text-xs md:text-base font-semibold'>Dark Mode</button>
                  </div>
            </div>
        </div>
        {children}
      </body>
    </html>
  );
}
